### ISSUE TITLE
Example of AST structure

### ISSUE THREAD

**Issue by bradleyayers** [icelab/draft-js-ast-exporter#1]
I took a look at this project and something that would make it a lot easier to assess would be an example in the README showing the structure of the AST and how it compares to the raw format that Draft.js currently supports.

**Comment by makenosound** [comment]
@bradleyayers Yes! Apologies for not including it earlier, I’ve still a little do to do make it easy to understand what the hell is going on. There’s now an example at: https://github.com/icelab/draft-js-ast-exporter/blob/master/docs/output.md
