### ISSUE TITLE
Draft-js 0.10.0 Migration

### ISSUE THREAD

**Issue by corbanbrook** [icelab/draft-js-ast-exporter#7]
Just a heads up that the Entity API has been deprecated in the latest draft-js release.
https://facebook.github.io/draft-js/docs/v0-10-api-migration.html

`Entity.get` will need to be changed.

This will also effect then ast-importer project as it uses `Entity.get` and `Entity.create`

**Comment by makenosound** [comment]
@corbanbrook Ta! I had noticed that go by, is on my list of things to get to :)

**Comment by makenosound** [comment]
@corbanbrook I’ve pushed up a couple of branches for the exporter and the importer that handle this API change. Mind giving them a run?

https://github.com/icelab/draft-js-ast-exporter/pull/8
https://github.com/icelab/draft-js-ast-importer/pull/6

**Comment by corbanbrook** [comment]
Great. I will have time on Monday to try it out.

**Comment by makenosound** [comment]
@corbanbrook Did you get a chance to test this out btw?

**Comment by corbanbrook** [comment]
Yeah, had a chance to look at it this morning. Everything looks good on both importer and exporter, no more deprecation warnings, all tests are passing and can edit my old content just fine.

**Comment by diiq** [comment]
Hi! Is there anything I can do to help get the PR for this issue merged? I'd love to eliminate the deprecation warnings this is causing.

**Comment by corbanbrook** [comment]
draft-js v0.10.0 has been out for 3 months now and I have been running this branch in production for about 2 months. I think it is safe to tag and merge into master.

**Comment by makenosound** [comment]
Sorry for the delay, folks! I’ve merged this and released as v2.0.0 (thanks for the reminder).
